### ISSUE TITLE
dogfood sourcecred/widgets

### ISSUE THREAD

**Issue by teamdandelion** [sourcecred/widgets#7]
We should have a contributor wall from `sourcecred/widgets` live within this repo itself. And we should find a way to keep it auto-updating (daily or weekly)

**Comment by Beanow** [comment]
There is an example of how this could be done with Drone.io and depending on sourcecred and widgets through submodules here: [sfosc/sourcecred@12bcd4e](https://github.com/sfosc/sourcecred/tree/12bcd4e03d2bb69bad15064012d3d69c6423c833)

However that brings me to another issue: #8 How to depend on sourcecred and widgets

Since CircleCI is used for Sourcecred, it should be pretty easy to port the Drone cronjob.
Should I go ahead with a submodule style dependency and create the demo?

**Comment by Beanow** [comment]
I don't think I can enable gh-pages by pushing to the branch https://github.com/sourcecred/widgets/tree/gh-pages

@decentralion could you enable it and set the CNAME as you like?

**Comment by teamdandelion** [comment]
@Beanow I think hosting it at `widgets.sourcecred.io` is a nice idea. It would be simpler to host it at `sourcecred.io/widgets` because then we don't need to muck around with CNAMEs, but using a subdomain it will never conflict with content at the main site.

I'm not too experienced with CNAMEs/DNS, but I think I've made the right update to sourcecred.io's DNS records. However, I think it will take a few hours to propagate. I'll keep an eye on it and make sure the site gets built.

**Comment by teamdandelion** [comment]
FYI, it seems to be working now: http://widgets.sourcecred.io/

**Comment by Beanow** [comment]
The github pages work. With #9 it should be automated and added to the readme
